// Code generated by protoc-gen-go. DO NOT EDIT.
// source: validate.proto

/*
Package gwproto is a generated protocol buffer package.

It is generated from these files:
	validate.proto

It has these top-level messages:
	FieldValidator
*/
package gwproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/protoc-gen-go/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FieldValidator struct {
	// Uses a Golang RE2-syntax regex to match the field contents.
	Regex *string `protobuf:"bytes,1,opt,name=regex" json:"regex,omitempty"`
	// Field value of integer strictly greater than this value.
	IntGt *int64 `protobuf:"varint,2,opt,name=int_gt,json=intGt" json:"int_gt,omitempty"`
	// Field value of integer strictly smaller than this value.
	IntLt *int64 `protobuf:"varint,3,opt,name=int_lt,json=intLt" json:"int_lt,omitempty"`
	// Used for nested message types, requires that the message type exists.
	MsgExists *bool `protobuf:"varint,4,opt,name=msg_exists,json=msgExists" json:"msg_exists,omitempty"`
	// Human error specifies a user-customizable error that is visible to the user.
	HumanError *string `protobuf:"bytes,5,opt,name=human_error,json=humanError" json:"human_error,omitempty"`
	// Field value of double strictly greater than this value.
	// Note that this value can only take on a valid floating point
	// value. Use together with float_epsilon if you need something more specific.
	FloatGt *float64 `protobuf:"fixed64,6,opt,name=float_gt,json=floatGt" json:"float_gt,omitempty"`
	// Field value of double strictly smaller than this value.
	// Note that this value can only take on a valid floating point
	// value. Use together with float_epsilon if you need something more specific.
	FloatLt *float64 `protobuf:"fixed64,7,opt,name=float_lt,json=floatLt" json:"float_lt,omitempty"`
	// Field value of double describing the epsilon within which
	// any comparison should be considered to be true. For example,
	// when using float_gt = 0.35, using a float_epsilon of 0.05
	// would mean that any value above 0.30 is acceptable. It can be
	// thought of as a {float_value_condition} +- {float_epsilon}.
	// If unset, no correction for floating point inaccuracies in
	// comparisons will be attempted.
	FloatEpsilon *float64 `protobuf:"fixed64,8,opt,name=float_epsilon,json=floatEpsilon" json:"float_epsilon,omitempty"`
	// Floating-point value compared to which the field content should be greater or equal.
	FloatGte *float64 `protobuf:"fixed64,9,opt,name=float_gte,json=floatGte" json:"float_gte,omitempty"`
	// Floating-point value compared to which the field content should be smaller or equal.
	FloatLte *float64 `protobuf:"fixed64,10,opt,name=float_lte,json=floatLte" json:"float_lte,omitempty"`
	// Used for string fields, requires the string to be not empty (i.e different from "").
	StringNotEmpty *bool `protobuf:"varint,11,opt,name=string_not_empty,json=stringNotEmpty" json:"string_not_empty,omitempty"`
	// Repeated field with at least this number of elements.
	RepeatedCountMin *int64 `protobuf:"varint,12,opt,name=repeated_count_min,json=repeatedCountMin" json:"repeated_count_min,omitempty"`
	// Repeated field with at most this number of elements.
	RepeatedCountMax *int64 `protobuf:"varint,13,opt,name=repeated_count_max,json=repeatedCountMax" json:"repeated_count_max,omitempty"`
	// Field value of length greater than this value.
	LengthGt *int64 `protobuf:"varint,14,opt,name=length_gt,json=lengthGt" json:"length_gt,omitempty"`
	// Field value of length smaller than this value.
	LengthLt *int64 `protobuf:"varint,15,opt,name=length_lt,json=lengthLt" json:"length_lt,omitempty"`
	// Field value of integer strictly equal this value.
	LengthEq         *int64 `protobuf:"varint,16,opt,name=length_eq,json=lengthEq" json:"length_eq,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *FieldValidator) Reset()                    { *m = FieldValidator{} }
func (m *FieldValidator) String() string            { return proto.CompactTextString(m) }
func (*FieldValidator) ProtoMessage()               {}
func (*FieldValidator) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *FieldValidator) GetRegex() string {
	if m != nil && m.Regex != nil {
		return *m.Regex
	}
	return ""
}

func (m *FieldValidator) GetIntGt() int64 {
	if m != nil && m.IntGt != nil {
		return *m.IntGt
	}
	return 0
}

func (m *FieldValidator) GetIntLt() int64 {
	if m != nil && m.IntLt != nil {
		return *m.IntLt
	}
	return 0
}

func (m *FieldValidator) GetMsgExists() bool {
	if m != nil && m.MsgExists != nil {
		return *m.MsgExists
	}
	return false
}

func (m *FieldValidator) GetHumanError() string {
	if m != nil && m.HumanError != nil {
		return *m.HumanError
	}
	return ""
}

func (m *FieldValidator) GetFloatGt() float64 {
	if m != nil && m.FloatGt != nil {
		return *m.FloatGt
	}
	return 0
}

func (m *FieldValidator) GetFloatLt() float64 {
	if m != nil && m.FloatLt != nil {
		return *m.FloatLt
	}
	return 0
}

func (m *FieldValidator) GetFloatEpsilon() float64 {
	if m != nil && m.FloatEpsilon != nil {
		return *m.FloatEpsilon
	}
	return 0
}

func (m *FieldValidator) GetFloatGte() float64 {
	if m != nil && m.FloatGte != nil {
		return *m.FloatGte
	}
	return 0
}

func (m *FieldValidator) GetFloatLte() float64 {
	if m != nil && m.FloatLte != nil {
		return *m.FloatLte
	}
	return 0
}

func (m *FieldValidator) GetStringNotEmpty() bool {
	if m != nil && m.StringNotEmpty != nil {
		return *m.StringNotEmpty
	}
	return false
}

func (m *FieldValidator) GetRepeatedCountMin() int64 {
	if m != nil && m.RepeatedCountMin != nil {
		return *m.RepeatedCountMin
	}
	return 0
}

func (m *FieldValidator) GetRepeatedCountMax() int64 {
	if m != nil && m.RepeatedCountMax != nil {
		return *m.RepeatedCountMax
	}
	return 0
}

func (m *FieldValidator) GetLengthGt() int64 {
	if m != nil && m.LengthGt != nil {
		return *m.LengthGt
	}
	return 0
}

func (m *FieldValidator) GetLengthLt() int64 {
	if m != nil && m.LengthLt != nil {
		return *m.LengthLt
	}
	return 0
}

func (m *FieldValidator) GetLengthEq() int64 {
	if m != nil && m.LengthEq != nil {
		return *m.LengthEq
	}
	return 0
}

var E_Field = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*FieldValidator)(nil),
	Field:         6800,
	Name:          "validate.field",
	Tag:           "bytes,6800,opt,name=field",
	Filename:      "validate.proto",
}

func init() {
	proto.RegisterType((*FieldValidator)(nil), "validate.FieldValidator")
	proto.RegisterExtension(E_Field)
}

func init() { proto.RegisterFile("validate.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 427 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x15, 0xb6, 0x6e, 0xa9, 0xbb, 0x95, 0xca, 0x02, 0xe9, 0x01, 0x9a, 0x88, 0xe0, 0x92,
	0x03, 0x4b, 0x24, 0x24, 0x2e, 0x13, 0x27, 0x50, 0xe8, 0xa5, 0x0c, 0x29, 0x07, 0x0e, 0x5c, 0x22,
	0xaf, 0x7d, 0x75, 0x2d, 0x39, 0x76, 0x66, 0xbf, 0xb2, 0xf2, 0x05, 0x38, 0xf3, 0x91, 0x51, 0x6c,
	0xb2, 0x05, 0x69, 0xc7, 0xf7, 0xfb, 0xbd, 0xfc, 0x1d, 0x5b, 0x7f, 0x36, 0xff, 0x29, 0xb4, 0xda,
	0x08, 0xc2, 0xa2, 0x73, 0x96, 0x2c, 0x4f, 0x87, 0xf9, 0x65, 0x26, 0xad, 0x95, 0x1a, 0xcb, 0xc0,
	0x6f, 0xf6, 0xdb, 0x72, 0x83, 0x7e, 0xed, 0x54, 0x47, 0xd6, 0xc5, 0xdd, 0x37, 0xbf, 0x8f, 0xd9,
	0xfc, 0x8b, 0x42, 0xbd, 0xf9, 0x1e, 0xbf, 0xb1, 0x8e, 0x3f, 0x63, 0x13, 0x87, 0x12, 0x0f, 0x90,
	0x64, 0x49, 0x3e, 0xad, 0xe3, 0xc0, 0x9f, 0xb3, 0x13, 0x65, 0xa8, 0x91, 0x04, 0x4f, 0xb2, 0x24,
	0x3f, 0xaa, 0x27, 0xca, 0xd0, 0x92, 0x06, 0xac, 0x09, 0x8e, 0xee, 0xf1, 0x8a, 0xf8, 0x05, 0x63,
	0xad, 0x97, 0x0d, 0x1e, 0x94, 0x27, 0x0f, 0xc7, 0x59, 0x92, 0xa7, 0xf5, 0xb4, 0xf5, 0xb2, 0x0a,
	0x80, 0xbf, 0x66, 0xb3, 0xdd, 0xbe, 0x15, 0xa6, 0x41, 0xe7, 0xac, 0x83, 0x49, 0x38, 0x88, 0x05,
	0x54, 0xf5, 0x84, 0xbf, 0x60, 0xe9, 0x56, 0x5b, 0x11, 0xce, 0x3b, 0xc9, 0x92, 0x3c, 0xa9, 0x4f,
	0xc3, 0xbc, 0xa4, 0x07, 0xa5, 0x09, 0x4e, 0x47, 0x6a, 0x45, 0xfc, 0x2d, 0x3b, 0x8f, 0x0a, 0x3b,
	0xaf, 0xb4, 0x35, 0x90, 0x06, 0x7f, 0x16, 0x60, 0x15, 0x19, 0x7f, 0xc5, 0xa6, 0x43, 0x34, 0xc2,
	0x34, 0x2c, 0xa4, 0xff, 0xb2, 0xf1, 0x41, 0x6a, 0x42, 0x60, 0x23, 0xb9, 0x22, 0xe4, 0x39, 0x5b,
	0x78, 0x72, 0xca, 0xc8, 0xc6, 0x58, 0x6a, 0xb0, 0xed, 0xe8, 0x17, 0xcc, 0xc2, 0xd5, 0xe6, 0x91,
	0x5f, 0x5b, 0xaa, 0x7a, 0xca, 0xdf, 0x31, 0xee, 0xb0, 0x43, 0x41, 0xb8, 0x69, 0xd6, 0x76, 0x6f,
	0xa8, 0x69, 0x95, 0x81, 0xb3, 0xf0, 0x42, 0x8b, 0xc1, 0x7c, 0xee, 0xc5, 0x57, 0x65, 0x1e, 0xdb,
	0x16, 0x07, 0x38, 0x7f, 0x6c, 0x5b, 0x1c, 0xfa, 0x5f, 0xd4, 0x68, 0x24, 0xed, 0xfa, 0xb7, 0x99,
	0x87, 0xa5, 0x34, 0x82, 0x25, 0x8d, 0xa4, 0x26, 0x78, 0x3a, 0x96, 0xab, 0xb1, 0xc4, 0x5b, 0x58,
	0x8c, 0x65, 0x75, 0x7b, 0x75, 0xcd, 0x26, 0xdb, 0xbe, 0x07, 0xfc, 0xa2, 0x88, 0xa5, 0x29, 0x86,
	0xd2, 0x14, 0xa1, 0x1f, 0xdf, 0x3a, 0x52, 0xd6, 0x78, 0xf8, 0xf3, 0x21, 0x4b, 0xf2, 0xd9, 0x7b,
	0x28, 0xee, 0x4b, 0xf7, 0x7f, 0x7d, 0xea, 0x18, 0xf3, 0xe9, 0xe3, 0x8f, 0x2b, 0xa9, 0x68, 0xb7,
	0xbf, 0x29, 0xd6, 0xb6, 0x2d, 0x6b, 0x61, 0x24, 0xea, 0x1a, 0x85, 0xc6, 0x72, 0x1b, 0x82, 0x2f,
	0xef, 0x9c, 0xe8, 0x2e, 0x87, 0x90, 0x52, 0xda, 0x7e, 0x2e, 0xe5, 0x5d, 0x90, 0x7f, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x4f, 0xfd, 0x54, 0x18, 0xd3, 0x02, 0x00, 0x00,
}
